# Generated by Django 5.2.17 on 2026-10-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('created', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['ip', 'created'], name='accounts_ipfailure_ip_created')],
            },
        ),
    ]
