# Generated by Django 5.2.17 on 2026-10-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ipfailure'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, unique=True)),
                ('blocked_until', models.DateTimeField()),
            ],
        ),
    ]
