# Generated by Django 5.2.17 on 2026-10-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_resetlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
